workflow:
  rules:
    # Start a pipeline if this is an MR.
    - if: $CI_MERGE_REQUEST_IID
    # Start a pipeline if a tag is created.
    - if: $CI_COMMIT_TAG
    # Start a pipeline if an event happened on "main" (e.g. an MR was merged).
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Start a pipeline if triggered by the web UI.
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - 00-initialization
  - 01-validation
  - 02-test-initial-state
  - 03-cleanup
  - 04-publish

default:
  image: "$PDG_CI_RUNNER_IMAGE"
  services:
    - name: "$PDG_CI_DOCKERHUB_MIRROR/docker:18.09-dind"
  tags:
    - k8s

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_API_VERSION: "1.39"
  KUBERNETES_CPU_REQUEST: "1250m"
  KUBERNETES_CPU_LIMIT: "2000m"
  KUBERNETES_MEMORY_REQUEST: "500Mi"
  KUBERNETES_MEMORY_LIMIT: "500Mi"
  KUBERNETES_POLL_TIMEOUT: 600

initialization:
  stage: 00-initialization
  script:
    - "./.gitlab-ci/00-initialization.sh"

validation:
  stage: 01-validation
  script:
    - "./.gitlab-ci/01-validation.sh"

test-initial-state:
  stage: 02-test-initial-state
  script:
    - "./.gitlab-ci/02-test-initial-state.sh"

cleanup:
  stage: 03-cleanup
  when: always
  script:
    - "./.gitlab-ci/03-cleanup.sh"

publish:
  stage: 04-publish
  rules:
    # Only formatted tags will publish. Format is <MAJOR>.<MINOR>-<YYYYMMDD>-<1-INDEX>
    #   e.g. 8.2-20201207-02 if this is the second tag created on December 12, 2020.
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\-\d{8}\-\d{2}$/
  script:
    - "./.gitlab-ci/04-publish.sh"

