# You should not need to modify this file. Please modify the variables in your .env file instead. The env-template.txt
# file contains an example .env file with default values pre-populated.
version: "2.4"

services:

  pingauthorize:
    image: ${PAZ_TUTORIALS_DEVOPS_REGISTRY}/pingauthorize:${PAZ_TUTORIALS_DEVOPS_TAG}
    container_name: pingauthorize
    environment:
      - SERVER_PROFILE_URL=${PAZ_TUTORIALS_PROFILE_URL:-https://github.com/pingidentity/pdg-tutorials.git}
      - SERVER_PROFILE_PATH=server-profiles/pingauthorize
      - SERVER_PROFILE_BRANCH=${PAZ_TUTORIALS_PROFILE_BRANCH:-main}
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "${PAZ_TUTORIALS_PAZ_PORT:-7443}:1443"

  pingauthorizepap:
    image: ${PAZ_TUTORIALS_DEVOPS_REGISTRY}/pingauthorizepap:${PAZ_TUTORIALS_DEVOPS_TAG}
    container_name: pingauthorizepap
    environment:
      - SERVER_PROFILE_URL=${PAZ_TUTORIALS_PROFILE_URL:-https://github.com/pingidentity/pdg-tutorials.git}
      - SERVER_PROFILE_PATH=server-profiles/pingauthorizepap
      - SERVER_PROFILE_BRANCH=${PAZ_TUTORIALS_PROFILE_BRANCH:-main}
      - PING_EXTERNAL_BASE_URL=${PAZ_TUTORIALS_PAP_HOSTNAME}:${PAZ_TUTORIALS_PAP_PORT}
      - HTTPS_PORT=1443
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "${PAZ_TUTORIALS_PAP_PORT:-8443}:1443"

  pingdirectory:
    image: ${PAZ_TUTORIALS_DEVOPS_REGISTRY}/pingdirectory:${PAZ_TUTORIALS_DEVOPS_TAG}
    container_name: pingdirectory
    environment:
      - SERVER_PROFILE_URL=${PAZ_TUTORIALS_PROFILE_URL:-https://github.com/pingidentity/pdg-tutorials.git}
      - SERVER_PROFILE_PATH=server-profiles/pingdirectory
      - SERVER_PROFILE_BRANCH=${PAZ_TUTORIALS_PROFILE_BRANCH:-main}
    env_file:
      - ${HOME}/.pingidentity/devops

  pingdataconsole:
    image: ${PAZ_TUTORIALS_DEVOPS_REGISTRY}/pingdataconsole:${PAZ_TUTORIALS_DEVOPS_TAG}
    container_name: pingdataconsole
    ports:
      - "${PAZ_TUTORIALS_CONSOLE_PORT:-5443}:8443"
